default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: balls_development

test:
  <<: *default
  database: balls_test

production:
  <<: *default
  database: balls_production
  username: balls
  password: <%= ENV['BALLS_DATABASE_PASSWORD'] %>
